### ISSUE TITLE
Unable to log in to localhost:3000 UI following torch steps

### ISSUE THREAD

**Issue by MattHinton** [arangoml/arangopipe#104]
Following the steps provided in the README, I am unable to log in to the ArangoML UI. 

Working remotely (port mapping 6529:localhost:8529 & 3000:localhost:3000) 

- docker run -p 6529:8529 -p 8888:8888 -p 3000:3000 --name arangopipes -it arangopipe/ap_torch
- docker exec -it arangopipes bash
- cd examples/pytorch
- python3
- >>> from ch_torch_linear_regression_driver import run_driver
- >>> run_driver()
- >>> exit(); exit
- navigate to either localhost:3000 or <remote_url>:3000 
- Insert "root" / "open sesame" 
- "Wrong ID or Password!"

**Comment by cw00dw0rd** [comment]
Hi @MattHinton ,
 This should be fixed in the most recent docker release. Please, let us know if you are still experiencing issue after updating.
Additionally, we will be doing a follow up release with some PyTorch specific notebooks with some different examples.
