### ISSUE TITLE
Create Demo Docker Image

### ISSUE THREAD

**Issue by joerg84** [arangoml/arangopipe#23]
Let us create a docker image which included arangoml pipeline, arangoDB, Jupyter, and TFX/scikit ...
This would allow for a demo with no further dependencies.
What do you think @rajivsam

**Comment by rajivsam** [comment]
Sure. I think doing this in two parts makes sense:

1. Create a docker image for everything mentioned above. It is worth noting that the TFX python install is quirky - not hard, but has some quirks.
2. Merge the docker images of arangodb and the output of the above step.

**Comment by joerg84** [comment]
I would probably use ArangoDB as the base image as it change less frequent

**Comment by rajivsam** [comment]
I was thinking out aloud about how I would create the docker image. I was just saying once I create the docker image for the Arangopipe components, I will test it and then once everything looks good, I will just merge it with the arangoDB base image. Basically that helps me partition the work into indepenedent parts - I will work on understanding the docker file for ArangoDB afer I have finished with the docker file segment for Arangopipe.

**Comment by rajivsam** [comment]
(1) Create docker image for arangopipe such that users can just pull this image and run it.
(2) Change arangopipe makefile to include targets to (a) build arangopipe image (b) tag it and push it to dockerhub.
(3) Copy the notebooks from the git repo into the docker build.
(4) In the getting started guide, explain the process of pulling the docker image and running it. Explain the examples (TFX integration example, hyperopt, MLFlow etc.) that are covered in the getting started guide.
(5) Make changes to git example notebooks to address using arangopipe from a PyPi package.

**Comment by rajivsam** [comment]
This has been completed
