### ISSUE TITLE
Covariate Shift Usecase

### ISSUE THREAD

**Issue by joerg84** [arangoml/arangopipe#8]
+ Notebook
+ Documentation
+ Blogpost

**Comment by rajivsam** [comment]
- [ ] Develop notebook skeleton
- [ ] Develop the API for covariate shift detection
- [ ] Develop the unit test for covariate shift detection
- [ ] Develop content for blog post
- [ ] Documentation (Is this for the API?)

**Comment by rajivsam** [comment]
Completed
