### ISSUE TITLE
Beginner Guide for PyTorch

### ISSUE THREAD

**Issue by bradjonesca** [arangoml/arangopipe#82]
There is a lot more momentum around PyTorch these days and not just because of today's announcement here: https://openai.com/blog/openai-pytorch/ .  Furthermore in the area of NLP, the soon to be released spaCy 3.0 will include the very new Thinc engine (v8) where they have far less friction using PyTorch (v 1.4) than TF.

**Comment by rajivsam** [comment]
Please see PR#95 @joerg84

**Comment by rajivsam** [comment]
@bradjonesca , please see:
https://github.com/arangoml/arangopipe/blob/master/examples/Arangopipe_with_Pytorch_Example.ipynb
for a colab notebook (no installs required). that shows how you can use pytorch for document classification and store meta-data about the experiment in arangopipe.
