### ISSUE TITLE
Basic UI

### ISSUE THREAD

**Issue by joerg84** [arangoml/arangopipe#9]

**Comment by rajivsam** [comment]
- [ ] Research UI use cases
- [ ] Review UI use cases

**Comment by rajivsam** [comment]
Administrative Application Development Tasks:
1. Design UI for Admin App
2. Implement UI Admin App
3. Integrate UI with backend
4. Integrate UI with Authentication and Authorization
5. Integrate UI with Arango UI
6. Develop Tests

Arangopipe UI Development Tasks:
1. Design search: 
- Search models, datasets, model parameters and featuresets by:
  - deployment tag
  - tag
  - date range
  - description
2. Hierarchial view of artifacts:
A tree representation to drill down on metadata. Initially a tree listing the projects the user is working is displayed. Each project can use multiple datasets. A user expands a project to view the datasets associated with the project. Then the user picks the dataset of interest and can drill down to the level of detail desired. See attachments for details.
[tree_visualization.gv.pdf](https://github.com/arangoml/arangopipe/files/3279645/tree_visualization.gv.pdf)
[meta_data_visualization.gv.pdf](https://github.com/arangoml/arangopipe/files/3279647/meta_data_visualization.gv.pdf)
Open Question: Should we be able to apply filters to the tree?
3. Develop tests for Search 

ArangoUI - Arangopipe UI Integration Tasks:
1. Design landing page or links from Arango UI to the Arangopipe apps for administration and analysis
2. Integrate this with authorization and authentication solution
3. Develop integration page/UI elements
4. Develop Tests for features

Integration testing of the above components.










--

**Comment by joerg84** [comment]
Can we expose those as user stories?

**Comment by rajivsam** [comment]
Completed
