### ISSUE TITLE
Unique Identifiers for Entities

### ISSUE THREAD

**Issue by cw00dw0rd** [arangoml/arangopipe#93]
Current Behavior:
Currently, it is possible to store entities that have the same name attribute. This can result in unexpected results when performing lookups.

Suggested Solution: 
Implement a uniqueness check at time of entity creation. A possible solution would be to set the _key value as the name supplied, this would require that the name is adjusted to be a valid _key handle.

**Comment by rajivsam** [comment]
We now have unique identifiers.
